### PR TITLE
feature: apply multiple plans to account plan

### PR DESCRIPTION
**Pull request by davidmeirlevy**

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
@Himasnhu-AT would you like to review my PR as well?

**Comment by Himasnhu-AT** [comment]
Looks good to me 👍

**Comment by davidmeirlevy** [comment]
in short, I'm working to create a many-to-many relation between accounts and plans.
so you can add multiple plans to the same account, and the state should be a sort of merge between all plans' fields.

it might also need some extra methods because the user will need to submit the account and later on - its associated plans that will affect the account plan state.

**Comment by davidmeirlevy** [comment]
i'm closing this PR.
I have a truly marvelous demonstration of this proposition that this PR comment is too narrow to contain.

**Pull request closed without merging**
