### PR TITLE
Feature/10 - Add A Nest Guard

### LINKED ISSUE #10: add nest.js guard middleware

### PR DESCRIPTION
**Pull request by eladabramovich**
Resolves #10, adding support for NestJs guard.
Added a new nest guard as part of the SDK library
as well as a NestJs demo app and documentation
for using PriciSDK with NestJs and using the guard
to help new users understand how the integration works.

Please note that to run the demo app server you will need
to manually transpile the SDK folder from TS to JS.

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
Thanks!
I'll run it today and check.
Probably I need to check other demos to make sure they're still work.

**Comment by davidmeirlevy** [comment]
@eladabramovich sorry for the conflicts..  i released the new docs.
please rebase to fix the conflicts. 🙏

**Comment by eladabramovich** [comment]
@davidmeirlevy, Done.

**Comment by davidmeirlevy** [comment]
@eladabramovich main was updated with the build steps. rebase again, please. : 🙏

**Comment by eladabramovich** [comment]
Can you please explain your intention for "In order to make it work"?
After rebasing I tested both demo apps and ran the test suite without any problem.

**Comment by davidmeirlevy** [comment]
The demo app nest didn't work.
It had problems with the guard location.
After adding the exports - everything works great.

**Comment by eladabramovich** [comment]
I created a fresh clone of my fork and was able to reproduce
the situation you talked about, seems like something in my original
clone made it pass without falling 😅
Anyway, I pushed the change you requested.

**Comment by davidmeirlevy** [comment]
Whenever I have those issues, I run: npx npkill 

It will change your life :)

**Pull request merged**
