### PR TITLE
custom errorMessage isn't required

### PR DESCRIPTION
**Pull request by madina0801**
Issue #31 
Made errorMessage field optional both in middleware and nest guard

### CODE REVIEW

**Comment by davidmeirlevy** [comment]
LGTM.

can you update the nest docs?
And maybe create same docs for express?

**Comment by madina0801** [comment]
Yes, I think I can!

**Comment by davidmeirlevy** [comment]
BTW, you're welcome to join the discord:

https://discord.gg/k9tH6Xtt

**Comment by davidmeirlevy** [comment]
I'll merge this PR.
Please update the docs on another PR.

**Pull request merged**
